### PR TITLE
Activate donate now button

### PR DESCRIPTION
**Pull request by Arceen**
**Description**
Added a popup on button click and dropped the background down, matched the buttons and animations a bit. Added a close button inside
#40 
image

https://github.com/Virtual4087/Tree2Hope/assets/24473439/b84a66ff-9a33-4bdd-9e88-59b86e28a71d

### CODE REVIEW

**Review by Virtual4087 — CHANGES_REQUESTED** [review]
Hey @Arceen Please attach a short screencast showcasing your changes.

**Comment by Arceen** [comment]
Sorry, forgot about it. Please check now!

**Review by Virtual4087 — COMMENTED** [review]
@Arceen looks good but there seems to be some merge conflicts in your pr. Resolve the conflicts and you are good to go.

**Comment by Arceen** [comment]
I've resolved the conflicts. Check please.

**Review by Virtual4087 — APPROVED** [review]

**Review by Virtual4087 — APPROVED** [review]

**Pull request merged**
