### PR TITLE
Centered last card in where we plant page

### PR DESCRIPTION
**Pull request by pra9patil**
As per your guide I centered last card 
will you please review it .

Thank you

### CODE REVIEW

**Comment by pra9patil** [comment]
@Virtual4087 please Accept my PR under hactoberfest

**Comment by pra9patil** [comment]
Sir I know I am not showing patience but I this is my 4 th PR in hacttoberfest so please review it

**Comment by pra9patil** [comment]
Updated

Screenshot (99)

**Comment by Virtual4087** [comment]
@pra9patil Check your pr results in smaller screens. The last country basically disappears because you've straight up given margin to it.

**Comment by pra9patil** [comment]
So should I do in oder to center it can please teach me

**Comment by Virtual4087** [comment]
@pra9patil I think we should close this issue as unplanned. I'll fix it myself whenever possible.

**Comment by pra9patil** [comment]
This is my last issue for hactoberfest as only 2 days remains so want to it , but it's ok 
thank you for guiding me

**Comment by pra9patil** [comment]
If you think there is any issue which I can contribute you can tell me  I can do it

**Comment by Virtual4087** [comment]
@pra9patil Try working on something you're sure you can do. You can then open a new pr and I'll accept it but make sure to create another branch that inherits from this repo's main branch.

**Comment by pra9patil** [comment]
Okk @Virtual4087 thank you so muchhh!!

**Pull request closed without merging**
