### PR TITLE
Made the Contact Us Page

### PR DESCRIPTION
**Pull request by Deepankar1484**
Hey @Virtual4087 ,
I have made the Contact-us page with a responsive design.
I have integrated the map in contact us page as well.
Screenshot 2024-10-19 at 12 09 25 PM
Screenshot 2024-10-19 at 12 10 18 PM

### CODE REVIEW

**Review by Virtual4087 — CHANGES_REQUESTED** [review]
@Deepankar1484 It would be great of you could attach a screenshot of your work.

**Comment by Deepankar1484** [comment]
Hey @Virtual4087 , You may check the changes now .

**Review by Virtual4087 — CHANGES_REQUESTED** [review]
I'm sorry but the appearance doesn't look very appealing. Maybe style it a little bit and fix the layout.

**Comment by Deepankar1484** [comment]
Ok, I will check and do some more changes

**Comment by Deepankar1484** [comment]
I am closing this pull request. Still working for a Contact us page that looks good.

**Comment by Virtual4087** [comment]
@Deepankar1484 Got it, I'll wait for your pr and if you feel like this might take too long, feel free to solve other issues.

**Pull request closed without merging**
