### PR TITLE
Enhancing events page

### PR DESCRIPTION
**Pull request by Ctrl-apk**
Assuming events card and event button i have made few changes in css of events making it more readable and attractive form

### CODE REVIEW

**Comment by Virtual4087** [comment]
Bruh that's not how you write css

**Review by Virtual4087 — CHANGES_REQUESTED** [review]
Not how you write css bro

**Comment by Ctrl-apk** [comment]
@Virtual4087 can you elaborate your issue so that i can solve it more clearly

**Comment by Virtual4087** [comment]
@Ctrl-apk You are supposed to enhance the events page by changing the css file used for events page. Just make sure your changes don't affect other functions. Also make sure you attach a screenshot/video showing the changes you made in the page

**Review by Virtual4087 — COMMENTED** [review]
@Ctrl-apk You are supposed to enhance the events page by changing the css file used for events page. Just make sure your changes don't affect other functions. Also make sure you attach a screenshot/video showing the changes you made in the page

**Pull request closed without merging**
