### PR TITLE
fix the position of the nav bar

### PR DESCRIPTION
**Pull request by Divii2205**
1. The position of the nav bar along with its elements has been fixed at the top of the webpage. 
2. A translucent background for the nav bar to enhance visibility has been added.

### CODE REVIEW

**Review by Virtual4087 — CHANGES_REQUESTED** [review]
Please attach a screenshot and request a review again

**Comment by Divii2205** [comment]
NavBarEnhancement

@Virtual4087

**Comment by Virtual4087** [comment]
Looks good @Divii2205

**Review by Virtual4087 — APPROVED** [review]

**Comment by Divii2205** [comment]
@Virtual4087 Thank you so much!

**Pull request merged**
