### PR TITLE
Enhance About Us page with glassmorphism effect for better visual appeal

### PR DESCRIPTION
**Pull request by DatHoang102003**
Hi,

I saw that another contributor has already submitted a pull request for this issue, and his solution looks great! However, I’ve also worked on this enhancement and would like to submit my version of the glassmorphism effect for the "About Us" page. I believe my version brings a slightly different approach that might offer another option for the team to consider.

I’ve attached a screenshot of the page for review, and I’m happy to make any adjustments based on feedback.

Thanks for the opportunity!
Screenshot 2024-10-09 190811

### CODE REVIEW

**Review by Virtual4087 — COMMENTED** [review]
The main concern is the color of the text container. It doesn't go too well with the background. If you can come up with some design to make it fit better with the background, I would gladly merge it.

**Comment by DatHoang102003** [comment]
Hi Virtual4087,

Thanks for the feedback! I've made updates to the text container to address your concerns about the color. I’ve darkened the background of the text container and adjusted the glass effect to better blend with the page background.
Here’s a screenshot of the updated design:
image
Let me know what you think, and if this works for you!

**Review by Virtual4087 — COMMENTED** [review]
I think you misunderstood what I meant. By background, I mean the whole background where the Image and the text is contained. It doesn't blend in with the background. You can discard the glass effect and just try to work on that.

**Comment by DatHoang102003** [comment]
Oh I'm understand, thank you for the clarify, gonna work on that now

**Review by Virtual4087 — COMMENTED** [review]
@DatHoang102003 I'll be closing this pr since the issue has already been solved but feel free to create more issues if you want. I'll make sure to assign them to you.

**Pull request closed without merging**
