### PR TITLE
About page

### LINKED ISSUE #21: Add "About Us" page
Create a separate html file for about us. The styling should be similar to index.html and  it should contain a detailed description of the website. The content inside the page doesn't matter a lot since i can change it anytime but the design should look good. You can also add quotes and all the other stuff that are found in a basic about us page.

Create a white box on top of the cover page and add your text in it. (Recommended)

### PR DESCRIPTION
**Pull request by laurenziello**
close #21

### CODE REVIEW

**Review by Virtual4087 — CHANGES_REQUESTED** [review]
@laurenziello The about us page looks very good, however, i would like to propose some changes. Can you place the about us info above the cover page? You can remove the "ABOUT US" text and replace it with the photo and text you've added below. You can give the text a white background so it becomes readable. I hope it's not too much work since you already have a container so you just need to move it a little higher. 

If you don't want to do that let me know I'll still accept the pr since you've already done a good job.

**Comment by laurenziello** [comment]
@Virtual4087 what do you think about?

**Review by Virtual4087 — COMMENTED** [review]
This looks good. I also noticed that you changed "About Us" with "our goals" in the navbar and menu. Can you change it back to about us and attach the link?

**Review by Virtual4087 — APPROVED** [review]

**Review by Virtual4087 — CHANGES_REQUESTED** [review]
You changed "About Us" with "our goals" in the navbar and menu. Change it back to about us and attach the link.

**Review by Virtual4087 — APPROVED** [review]

**Pull request merged**
