### PR TITLE
Fixed "Donate Us" button popup in the Navbar

### LINKED ISSUE #109: Change "Donate Us" button in the Navbar
When you click on "Donate us " button in the Navbar, the screen is scrolled down to "Just $1 plants a tree" section but a popup also appears. Remove the popup from "Donate us" button and just keep the scroll effect.

Note: Don't wait to get assigned. The first pr that looks good gets merged

### PR DESCRIPTION
**Pull request by LismaxB**
Fixes #109

### CODE REVIEW

**Review by Virtual4087 — CHANGES_REQUESTED** [review]
Now "JUST $1 PLANTS A TREE" button doesn't trigger the popup either. Please only disable the popup for "DONATE NOW" button

**Review by Virtual4087 — APPROVED** [review]

**Comment by Virtual4087** [comment]
Thanks for your contribution @LismaxB. Feel free to create new issues/prs

**Comment by LismaxB** [comment]
Glad to help! Feel free to tag me for new issues/PRs

**Comment by Virtual4087** [comment]
@LismaxB please go through the website and if you feel like something could be done better, raise an issue and I'll make sure to assign it to you under hacktoberfest label.

**Pull request merged**
