### PR TITLE
Added links to the countries

### PR DESCRIPTION
**Pull request by manan18**

### CODE REVIEW

**Comment by manan18** [comment]
Added Wikipedia links to all the countries:
Screenshot 2023-10-26 165254

**Review by Virtual4087 — APPROVED** [review]

**Comment by Virtual4087** [comment]
Great work @manan18. Thanks for contributing.

**Review by Virtual4087 — CHANGES_REQUESTED** [review]
@manan18 I think you forgot to add  target="_blank" in the links. Do that are we're good to go.

**Comment by manan18** [comment]
@Virtual4087 Please have a look again.

**Review by Virtual4087 — APPROVED** [review]

**Pull request merged**
