### PR TITLE
:sparkles:[feat][added background to the image and context in about Us ]

### PR DESCRIPTION
**Pull request by Ankitv003**
Hey shovit, did some changes in about page , let me know if anything more needs to be done, this will be my first pr for hacktoberfest!

### CODE REVIEW

**Comment by Ankitv003** [comment]
fix#87

**Review by Virtual4087 — COMMENTED** [review]
Hey @Ankitv003 can you attach a screenshot of your work?

**Comment by Ankitv003** [comment]
sure , here it is
Screenshot (137)

**Review by Virtual4087 — CHANGES_REQUESTED** [review]
You don't need to add separate background for the image and the text. Add all of it inside a single white box.

Also, it would be great if you could darken the text a little.

**Comment by Ankitv003** [comment]
ok, will make the changes

**Comment by Ankitv003** [comment]
hey shovit , is this good , should i make a pr?
Screenshot (139)

**Comment by Virtual4087** [comment]
@Ankitv003 that's perfect!

**Review by Virtual4087 — APPROVED** [review]

**Comment by Ankitv003** [comment]
let me add the  changes , i haven't added the change to this pr. how should i do that? create a new pr?

**Comment by Virtual4087** [comment]
ohh i thought you already made them. No worries open a new pr i'll accept it

**Comment by Ankitv003** [comment]
ok, i created a new pr , thanks for letting me contribute!!

**Pull request merged**
