### PR TITLE
docs: added contributors bot

### PR DESCRIPTION
**Pull request by dakshsinghrathore**
This PR resolves the issue #45 
Kindly review the PR and merge it, under "hacktoberfest-accepted" label ! 😀

### CODE REVIEW

**Review by Virtual4087 — APPROVED** [review]

**Comment by Virtual4087** [comment]
@dakshsinghrathore All the contributors were removed when i merged your pr. Please test it on your repo once again and submit a new pr.

**Comment by dakshsinghrathore** [comment]
@Virtual4087 Inorder to keep the info of earlier contributors intact we need to add them manually and then for any new contributor whole process will be automated !

**Comment by Virtual4087** [comment]
ohh ok i'll give it a try

**Comment by dakshsinghrathore** [comment]
Hey @Virtual4087 If you are still facing the issue kindly install the all contributor from [here](https://allcontributors.org/docs/en/bot/installation)  and select this repo from your profile

**Pull request merged**
