### PR TITLE
improve ui for About page and some css changes

### PR DESCRIPTION
**Pull request by DhruvSeth18**
Enhanced About page design with layout improvements, updated content, and styling tweaks. Added sticky footer and placed images for a better user experience.

Screenshots:-
Screenshot 2024-10-23 172319
Screenshot 2024-10-23 172237

### CODE REVIEW

**Comment by Virtual4087** [comment]
@DhruvSeth18 The previous about us looks better imo. In your Pr, the text color doesn't match, the image looks awful, the dimensions aren't proper. Just decrease the space between about us section and the footer, don't change anything else.

**Comment by DhruvSeth18** [comment]
like this .
image_2024-10-23_210607628

**Comment by DhruvSeth18** [comment]
@Virtual4087

**Comment by Virtual4087** [comment]
@DhruvSeth18 discard all the changes you made and only remove the gap between the footer and about us section.

**Pull request closed without merging**
