### PR TITLE
Made a responsive and dashing contact us page 

### PR DESCRIPTION
**Pull request by Deepankar1484**
Here are some pics 
Screenshot 2024-10-19 at 4 23 57 PM
Screenshot 2024-10-19 at 4 25 21 PM
Screenshot 2024-10-19 at 4 25 40 PM
Screenshot 2024-10-19 at 4 25 53 PM

### CODE REVIEW

**Review by Virtual4087 — CHANGES_REQUESTED** [review]
@Deepankar1484 That looks a lot better. Just one thing tho, Could you also style the "back" button in the contact page? It doesn't look good right now.

**Comment by Deepankar1484** [comment]
Yes sure, on it.

**Comment by Deepankar1484** [comment]
please check it now 
Screenshot 2024-10-19 at 6 24 22 PM

**Review by Virtual4087 — APPROVED** [review]

**Comment by Virtual4087** [comment]
@Deepankar1484 Thanks for the contribution

**Comment by Deepankar1484** [comment]
Hey @Virtual4087 , Thanks man.

**Comment by Virtual4087** [comment]
@Deepankar1484 I should be thanking you instead for the contribution. Feel free to open new issues.

**Pull request merged**
