### PR TITLE
Attempt at fixing greetings.yml

### PR DESCRIPTION
**Pull request by SeaBebop**
Added a conditional that covers both pr and issue events

### CODE REVIEW

**Comment by Virtual4087** [comment]
does it work for both pr and issues? If yes can you send screenshots of each from where you tested it?

**Comment by SeaBebop** [comment]
https://github.com/Virtual4087/Tree2Hope/assets/54507045/be561118-b2bb-422a-a5bc-7b7669d3f897

This is a test I did with my own private resp, I will make it public in case you need to see it yourself. It also contains the same greeting code as shown form the beginning of the video.

**Review by Virtual4087 — COMMENTED** [review]
Great work! Can you just add "@" in front of the username so they actually get tagged? Do this and I'll merge the pr.

**Comment by SeaBebop** [comment]
image

image
Yes I can. Here ya go

**Review by Virtual4087 — APPROVED** [review]

**Pull request merged**
