### PR TITLE
issueSolved for responsiveness in small size mobile

### PR DESCRIPTION
**Pull request by 08Uzair**
Now it is also  Responsive for the small screen size mobile too .
I had made the another file for the responsiveness  which is named as "responsiveness.css"
and the another file which have all included the general file  is the "style.css"

### CODE REVIEW

**Review by Virtual4087 — CHANGES_REQUESTED** [review]
Can you also include some screenshots or screencasts that show your work? (screencast preferred)

**Review by Virtual4087 — COMMENTED** [review]
@08Uzair Upload a short screencast showing the changes you made and I'll merge it

**Comment by 08Uzair** [comment]
https://youtu.be/XTe1Wp3FWlw?feature=shared

**Review by Virtual4087 — APPROVED** [review]

**Comment by Virtual4087** [comment]
Please keep your branch up to date from next time

**Review by Virtual4087 — APPROVED** [review]

**Pull request merged**
