### PR TITLE
Update style.css for Gapping

### LINKED ISSUE #5: Fix gapping
Everything looks really congested right now. Fix the gap between all the sections in the website.

### PR DESCRIPTION
**Pull request by AmosBlack**
Resolved #5

### CODE REVIEW

**Comment by AmosBlack** [comment]
https://github.com/Virtual4087/Tree2Hope/assets/80113495/9188dfe9-d4de-4344-ad2f-49a588fc1c4c

**Comment by AmosBlack** [comment]
If you find the work worthwhile, please add the hacktober-fest label, thanks.

P.S tagging the issue doesn't count the labels

**Comment by Virtual4087** [comment]
Increase the vertical spacing a little more and also increase the spacing between countries in "Where we plant" section if you can

**Review by Virtual4087 — CHANGES_REQUESTED** [review]
Increase the vertical spacing a little more and also increase the spacing between countries in "Where we plant" section if you can

**Comment by AmosBlack** [comment]
> Increase the vertical spacing a little more and also increase the spacing between countries in "Where we plant" section if you can

Can you elaborate on what you mean by "vertical spacing"

**Comment by Virtual4087** [comment]
> > Increase the vertical spacing a little more and also increase the spacing between countries in "Where we plant" section if you can
> 
> Can you elaborate on what you mean by "vertical spacing"

I mean The space between the "Where we plant" "Our goals" and similar sections.

**Comment by Virtual4087** [comment]
Screenshot_2023-10-14-17-16-34-04_40deb401b9ffe8e1df2f1cc5ba480b12

These parts to be specific. Increase the gap between all these sections.

**Comment by AmosBlack** [comment]
image
Fixed the image spacing issue.

**Comment by AmosBlack** [comment]
image
image
image
image

Does this look good ?

**Comment by Virtual4087** [comment]
Can you send a video like you did the last time?

**Comment by AmosBlack** [comment]
https://github.com/Virtual4087/Tree2Hope/assets/80113495/bb09b944-7e2a-49b4-99c9-28c2e83fa2d2

**Review by Virtual4087 — APPROVED** [review]

**Review by Virtual4087 — APPROVED** [review]

**Review by Virtual4087 — APPROVED** [review]

**Comment by AmosBlack** [comment]
If you find my work satisfactory, please add the hacktoberfest-accepted label to this PR, thanks.

P.S tagging the issue doesn't copy the labels 😄

**Comment by Virtual4087** [comment]
Done and I didn't mean it copies the label but it'll still count as a valid pr in hacktoberfest

**Comment by Virtual4087** [comment]
Thank you for your contribution @AmosBlack.

**Pull request merged**
