### PR TITLE
 Appearance enhancements made

### PR DESCRIPTION
**Pull request by nileshkr022**
Made the border shadow of cards in our goals section uniform and added suitable transition on hovering.
Enhanced footer by giving proper padding to sections and changing colors of certain section in it.

### CODE REVIEW

**Review by Virtual4087 — CHANGES_REQUESTED** [review]
Please provide the image/video of the changes you made and request a review

**Comment by nileshkr022** [comment]
https://github.com/user-attachments/assets/72d2317d-4d2b-4b6f-b1dc-be636ff2d027

@Virtual4087 Made the border shadow of cards in our goals section uniform and added suitable transition on hovering.
Enhanced footer by giving proper padding to sections and changing colors of certain section in it.

**Comment by Virtual4087** [comment]
@nileshkr022 The padding seems nice. But I don't think the hover effect is needed so you can remove it

**Review by Virtual4087 — CHANGES_REQUESTED** [review]
Please request a review after removing the hover effect

**Comment by nileshkr022** [comment]
> Please request a review after removing the hover effect

what i have to remove? The color or scaling or both

**Comment by Virtual4087** [comment]
@nileshkr022 just keep the changes made to the footer section. You can discard the other changes or maybe try making the hover effect more visually appealing if you can. It's fine either way, I'll merge it once you do that

**Comment by nileshkr022** [comment]
https://github.com/user-attachments/assets/7b67475f-214c-4dee-be42-1f1bb2bec67c

**Review by Virtual4087 — CHANGES_REQUESTED** [review]
Looks good @nileshkr022 but there seems to be some conflict since I just merged another pr. Please solve it and we are good to go.

**Pull request closed without merging**
