### PR TITLE
Added relevant text in about us page

### PR DESCRIPTION
**Pull request by manan18**

### CODE REVIEW

**Comment by manan18** [comment]
Hello @Virtual4087 , I initiated a Pull Request #96  , but it shows merging is blocked. Can you please look into the issue?

**Review by Virtual4087 — CHANGES_REQUESTED** [review]
Attach a screenshot of your work :)

**Comment by manan18** [comment]
Previous:
Screenshot 2023-10-26 162325

Current:
Screenshot (639)

**Comment by Virtual4087** [comment]
@manan18 Look good! Thank you for your contribution.

**Review by Virtual4087 — APPROVED** [review]

**Comment by manan18** [comment]
Sure, Happy to Help :)

**Pull request merged**
