### PR TITLE
[FIX] #105added gap between our goals and footer section

### LINKED ISSUE #105: Increase the gap between Our goals and footer section
Note: Can start working immediately without getting assigned. The first pr gets merged.

### PR DESCRIPTION
**Pull request by Vinayyy19**
# Pull Request Template

## Description
To add a gap between the "Our Goals" section and the footer section, I have added a line in CSS that creates a gap between the two sections.

## Related Issue
Fixes #105

## Changes Made
Given a margin from the top of the footer to increase the gap of **100px**.

## Screenshots 
image

## Checklist
- [x] I have read the contributing guidelines.
- [x] I have tested my changes.
- [x] My code follows the code style of this project.

### CODE REVIEW

**Comment by Vinayyy19** [comment]
@Virtual4087  could you review and merge it, if it fullfill your requirement

**Review by Virtual4087 — CHANGES_REQUESTED** [review]
Please don't use static values like px

**Comment by Vinayyy19** [comment]
hey @Virtual4087 i have replaced px with rem could you please check it out

**Review by Virtual4087 — APPROVED** [review]
looks good

**Pull request merged**
