### PR TITLE
Closes #20

### LINKED ISSUE #20: Enhance README.md
As of now, the readme only contains a short description of the website. Add stuff like hactoberfest contribution, basic contribution rules, small setup guide and style them properly. You can also add other things such as license, contributors profile's if you wish.

### PR DESCRIPTION
**Pull request by KaneshiroKeola**
Hi @Virtual4087 I Have Added extra info to the Readme file as well as added a contribution list and a short description of the rules and what is expected in the process of contributing to this Project.

Closes #20 

If you could please mark this as completed for Hacktober contribution that would be great! Thank you so much.

### CODE REVIEW

**Review by Virtual4087 — CHANGES_REQUESTED** [review]
Hi @KaneshiroKeola, Thanks for the contribution however i would like to propose some changes. 
- Don't use bullet points in the introduction area. It should be a paragraph. 
- The contributors section should show the profile of all the contributors like [this](https://github.com/Dun-sin/Whisper#-thanks-to-all-contributors)

Make these changes and don't forget to tag the issue in your pr

**Comment by KaneshiroKeola** [comment]
Ok thankyou. 
also how do i tag the issue in my pr?

**Comment by Virtual4087** [comment]
@KaneshiroKeola You can write "Closes #issue_number". Replace issue_number with the actual issue number which in this case is 20.

**Comment by KaneshiroKeola** [comment]
@Virtual4087 
I have Completed the changes that you requested and I have tagged the issue in my pr.

**Review by Virtual4087 — APPROVED** [review]

**Review by Virtual4087 — CHANGES_REQUESTED** [review]
Everything looks good but there seems to be a slight spelling error at line 1 of Rules section (Contribute is spelled contrite). Also you didn't need to change the  title of your pr. You can add "Closes #issue_number" in the description of your pr and remove the quotations. Fix this and we are good to go

**Comment by KaneshiroKeola** [comment]
@Virtual4087 
Hi, I have fixed the grammar issues and removed the quotations.

**Comment by KaneshiroKeola** [comment]
If you could please add the Hacktoberfest-accepted label to my pr when you approve it that would be great so that i get credit for the hacktober participation. Thankyou!

**Review by Virtual4087 — APPROVED** [review]

**Review by Virtual4087 — APPROVED** [review]

**Pull request merged**
