### PR TITLE
Improved Visual Cohesion on About Us Page

### LINKED ISSUE #107: Change About Us page design
The about us page doesn't blend in with the background. Change the background where the text is written. Maybe you could give it a blurry glass effect. 

Note: Don't wait to get assigned. The first pr that looks good gets merged. Also don't forget to add a ss of your work.

### PR DESCRIPTION
**Pull request by admwln**
Fixes #107 : Change About Us page design

I have enhanced the visual cohesion between the background of the About Me page and the foreground content by:

    -Adding a radial gradient to the background of the main container.
    -Applying a blurry backdrop-filter to the container to create a subtle blur effect.

This change helps unify the background and foreground elements, creating a smoother and more cohesive design. The effect is subtle but noticeable, and it improves the overall aesthetics of the page without being distracting.

Testing:

    -Verified the visual changes on Chrome and Firefox.
    -Ensured the layout remains responsive and the effect renders properly on desktop and mobile.

### CODE REVIEW

**Review by Virtual4087 — COMMENTED** [review]
Hey @admwln. Could you please provide a screenshot of the result.

**Review by Virtual4087 — COMMENTED** [review]
Looks good but I think changing the bg color itself would make it better. Could you try that once? If not, I'll merge this pr cause this doesn't look bad either. Try making the "about us" block not stand out too much.

**Review by Virtual4087 — COMMENTED** [review]
Please add a ss of your changes

**Comment by admwln** [comment]
I had another go of it, with a more subtle background, and some minor style changes:
desktop
mobile

Please note that I have added a background color to body for smaller screens. The following image illustrates what happens without said change. The problem seems to arise because of how the background photograph is implemented, however, I could not find a satisfying solution.
mobile-broken

**Review by Virtual4087 — COMMENTED** [review]
Looks good but there seems to be some conflict in your branch cause I just merged another pr

**Comment by admwln** [comment]
Oh I see, it seems that pr #121, which is already merged to main, fixes #107 (that the present pr tries to solve). The two prs are not compatible. It's one or the other, as far as I can tell. I have no problem with you choosing the other solution over mine. It was a fun exercise!

**Review by Virtual4087 — COMMENTED** [review]
@admwln True but I don't want to not merge your changes after you've already done so much. So maybe you could create another fork and just change the text format like color and stuff to make it more clean? The current "About Us" section's text content is not very appealing. If you can you can make it more minimalistic.

**Comment by admwln** [comment]
Thank you, @Virtual4087.

See pr #122.

**Comment by Virtual4087** [comment]
@admwln Done I'll be closing this pr. Thanks for the help.

**Pull request closed without merging**
